openapi: "3.0.0"
info:
  version: v1
  title: test-api-spec-for-support-case
paths: 
  /testEndpoint1/{uriParam1}:
    get:
      parameters:
        - $ref: "common-parameters.yaml#/components/parameters/UriParam1"
      description: Test endpoint 1.
      responses:
        '200':

  /testEndpoint2/{uriParam2}:
    get:
      parameters:
        - $ref: "common-parameters.yaml#/components/parameters/UriParam2"
      description: Test endpoint 2.
      responses:
        '200':
