language: node_js
node_js: 8
sudo: required
before_script:
- npm install -g polymer-cli
- polymer install --variants
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run polymer test --plugin local
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --job-name
  "api-method-documentation:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER};
  fi
cache:
  directories:
  - node_modules
after_success:
- node tasks/ci.js
env:
  global:
  - secure: UuzCmOz8XUm1eAm1qmRkr4sweiAdgBBTcWR+1wtdlJCAdSAyHFcNO1h7paGYllI5jie9lbg3YHS1yO2G0Tvr1emfwpa4azDNNaMgXZ6+JAQ9KHsDhYNqenoBLt/Y7ikGLAkTwCwMm1FxaS7l7zfe/X+gLpYpOFFoBgmPaCMo37lVz6MaZKKWc+iJqqfNXPs7NVTcV5kt/76TclFbpORPL3+l7MeiylgiCleeKxERv1+QVHh0x+4cUhcnkGmSZdSoJD3lbG58xlhOpMgYYaAk4SQU5YBbtS+oamqkkG/0NDdNhdWHAuiE4hN+8S7wmrOiP9EKFcaLJ0aOuToMsK7UwANA4k/fsrGKRPuHOfBp2xgWXh0HFH3Ug6PVC8oWVWjlFvkTT17fFmL5GKIigBAajdhU82OAOHQ8Hq6QOF+dKJNMXWdWhVmeFWackUosxtNUO6l49Wwr/NpdONrl9UmgkJAbhSGb+j3Ze9fN+wd1PwcXus4+QhCA8CApKnC7n9ETbGay+xh3pbDG0jK0P9drJ4AyOpDdOdi9A4+8pZkeEl/+Sq2KdLGTaGKzbaGi4+QytNCkv9uPvLsECuer5Fyq5UJ00xZoSs9NQUypuUAEO5SlCpjM+FHATu/GKxW903M5fM5ravyiAY5QlwuBpL+4nvPqRIK20vv8gT1bk3BFBNY=
  - secure: D2Ape0NuS1I6m6N4WTXvybMNORBJjC6+aJAQkDfkj69bu/3DaSidKc3MzfXK8HU2P4ql3oe361zpZ5U+EF7BJwd4F+xPHIHuVVCAJ0OZANU+lJZdfEFwV57D9JoP79z/FVn4BdJeEZtXdfnCVGfQRqDHgiZokduWK/8YHvryOxw++2MxAuneIY5VAvnPY1rwPv/7hjOfFjHXK8Hgi0MxBfYHh/tWD9avL7EA/twQj1ugM2bwKQyFNEYBQfkvMd4lgzyyvhniZ1kMpBNvQNbmYRMjoP0WB4mkOCe5ImEsVSAAfGTAiO40ao5NdBY6hK60RIsLT6x6H7QmzCqxoOtloh4nJp7oJdX4OwVTAZW/xg9Bn0l2RgJjNlG21Lp6MzoJwjGWLY3ARvgGV+QDK0Fq8PjeexuRHWyMyHhsCJZLRK4CkY2+ec7USbnfp6h8OblUg54wD5JOuJ6Jz1GImw05pMGiJ8WDolvtnfqv0+JeJK/OGmc/2++xuSrYFMcy+gMQHo4LDvh6Z0iiF8sJ+2SNMUyVF8tNZI8H4lLgUVnvRX+fzNyZi7UqNXDFhDopeYRJR6X53MzAWAU0MIPmfmMvNHkgaZcc/9K0bVpzFjQvpM8L0ALo8+xGXu+GbpMZTUDvTxtl+WR51JyDdg1CRYfEGT9Fadbah92L/48iI8ZLGFw=
